// AUTO-GENERATED by scripts/generate-gifs.mjs. Do not edit by hand.

export type GifEntry = {
  id: string;
  src: string;
  name: string;
  category: string;
};

export const GIFS: GifEntry[] = [
  {
    "id": "gifs/beg1.webp",
    "src": "/gifs/beg1.webp",
    "name": "beg1",
    "category": "beg"
  },
  {
    "id": "gifs/beg2.webp",
    "src": "/gifs/beg2.webp",
    "name": "beg2",
    "category": "beg"
  },
  {
    "id": "gifs/money1.webp",
    "src": "/gifs/money1.webp",
    "name": "money1",
    "category": "money"
  },
  {
    "id": "gifs/money2.webp",
    "src": "/gifs/money2.webp",
    "name": "money2",
    "category": "money"
  },
  {
    "id": "gifs/money3.webp",
    "src": "/gifs/money3.webp",
    "name": "money3",
    "category": "money"
  },
  {
    "id": "gifs/money4.webp",
    "src": "/gifs/money4.webp",
    "name": "money4",
    "category": "money"
  },
  {
    "id": "gifs/money5.webp",
    "src": "/gifs/money5.webp",
    "name": "money5",
    "category": "money"
  },
  {
    "id": "gifs/owl1.webp",
    "src": "/gifs/owl1.webp",
    "name": "owl1",
    "category": "owl"
  },
  {
    "id": "gifs/owl2.webp",
    "src": "/gifs/owl2.webp",
    "name": "owl2",
    "category": "owl"
  },
  {
    "id": "gifs/owl3.webp",
    "src": "/gifs/owl3.webp",
    "name": "owl3",
    "category": "owl"
  },
  {
    "id": "gifs/owl4.webp",
    "src": "/gifs/owl4.webp",
    "name": "owl4",
    "category": "owl"
  }
];

export const GIF_CATEGORIES: string[] = [
  "beg",
  "money",
  "owl"
];
