#!/usr/bin/env node
// Walks public/gifs/ and emits a typed manifest at lib/gifs.generated.ts.
// Categories derived from filename prefix (letters before any trailing digits).
// Run automatically via predev/prebuild; safe to re-run.

import { readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, parse, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const GIF_DIR = join(ROOT, 'public', 'gifs');
const OUT = join(ROOT, 'lib', 'gifs.generated.ts');

const EXTS = new Set(['.gif', '.webp', '.png', '.jpg', '.jpeg', '.mp4', '.webm']);

function walk(dir, base = dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full, base));
    } else if (EXTS.has(parse(entry.name).ext.toLowerCase())) {
      out.push(full);
    }
  }
  return out;
}

function deriveCategory(name) {
  // beg1 -> beg, money10 -> money, party_dance -> party_dance
  const trimmed = name.replace(/[-_ ]?\d+$/, '');
  return trimmed || name;
}

const files = walk(GIF_DIR).sort();
const entries = files.map((abs) => {
  const rel = relative(join(ROOT, 'public'), abs).split(/[\\/]/).join('/');
  const { name } = parse(abs);
  return {
    id: rel,
    src: '/' + rel,
    name,
    category: deriveCategory(name).toLowerCase(),
  };
});

const categories = Array.from(new Set(entries.map((e) => e.category))).sort();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/generate-gifs.mjs. Do not edit by hand.

export type GifEntry = {
  id: string;
  src: string;
  name: string;
  category: string;
};

export const GIFS: GifEntry[] = ${JSON.stringify(entries, null, 2)};

export const GIF_CATEGORIES: string[] = ${JSON.stringify(categories, null, 2)};
`,
);

console.log(`gifs: ${entries.length} files, ${categories.length} categories → ${relative(ROOT, OUT)}`);
